In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import time
from rtm_pymmcore.data_structures import Channel, StimTreatment, SegmentationMethod
import rtm_pymmcore.utils as utils
from pprint import pprint
import pandas as pd

In [3]:
from rtm_pymmcore.agents.bo_optimization_gpax import (
    BOptGPAX,
    BO_Parameter,
    BO_Objective,
    StandardScalerBounds,
    BO_Covariate,
)

In [4]:
bo_params = [
    BO_Parameter(name="stim_power", param_type="int", bounds=(0, 100), spacing=10),
    BO_Parameter(
        name="exposure_time", param_type="int", bounds=(100, 1000), spacing=100
    ),
]
bo_covariates = [BO_Covariate(name="covariate")]
bo_objective = BO_Objective(name="metric", goal="maximize")

In [5]:
test = BOptGPAX(
    pipeline="pipeline",
    microscope="mic",
    parameters_to_optimize=bo_params,
    objective_metric=bo_objective,
    bo_covariates=bo_covariates,
    n_iterations=10,
)

In [6]:
test.total_parameter_space

array([[   0,  100],
       [   0,  200],
       [   0,  300],
       [   0,  400],
       [   0,  500],
       [   0,  600],
       [   0,  700],
       [   0,  800],
       [   0,  900],
       [   0, 1000],
       [  10,  100],
       [  10,  200],
       [  10,  300],
       [  10,  400],
       [  10,  500],
       [  10,  600],
       [  10,  700],
       [  10,  800],
       [  10,  900],
       [  10, 1000],
       [  20,  100],
       [  20,  200],
       [  20,  300],
       [  20,  400],
       [  20,  500],
       [  20,  600],
       [  20,  700],
       [  20,  800],
       [  20,  900],
       [  20, 1000],
       [  30,  100],
       [  30,  200],
       [  30,  300],
       [  30,  400],
       [  30,  500],
       [  30,  600],
       [  30,  700],
       [  30,  800],
       [  30,  900],
       [  30, 1000],
       [  40,  100],
       [  40,  200],
       [  40,  300],
       [  40,  400],
       [  40,  500],
       [  40,  600],
       [  40,  700],
       [  40,

In [7]:
demo_df = pd.DataFrame(
    {
        "stim_power": [10, 20, 30],
        "exposure_time": [300, 600, 900],
        "metric": [0.5, 0.6, 0.4],
        "covariate": [1.0, 1.5, 2.0],
    }
)


x = test._extract_x_from_df(demo_df)
y = test._extract_y_from_df(demo_df)


bounds = []
log_scale = []

for bo_param in bo_params:
    bounds.append(bo_param.bounds)
    log_scale.append(bo_param.log_scale)

for bo_covariate in bo_covariates:
    bounds.append(bo_covariate.bounds)
    log_scale.append(bo_covariate.log_scale)


x_scaler = StandardScalerBounds()
x_scaler.fit_transform(x, bounds=bounds, log_scale=log_scale)

y_scaler = StandardScalerBounds()
y_scaler.fit_transform(y)

Array([[ 0.       ],
       [ 1.2247452],
       [-1.2247448]], dtype=float32)

In [ ]:
x_scaler = StandardScalerBounds()
bounds, log_scale = test._get_bounds_and_log_scale()

X_scaled = x_scaler.fit_transform(test.x_unmeasured, bounds=bounds, log_scale=log_scale)
print(X_scaled)
X_selected_scaled, selected_indices = test._extract_spread_points(X_scaled, k=3)
X_selected = x_scaler.inverse_transform(X_selected_scaled)

[[-1.         -1.        ]
 [-1.         -0.7777778 ]
 [-1.         -0.5555556 ]
 [-1.         -0.33333334]
 [-1.         -0.11111111]
 [-1.          0.11111111]
 [-1.          0.33333334]
 [-1.          0.5555556 ]
 [-1.          0.7777778 ]
 [-1.          1.        ]
 [-0.8        -1.        ]
 [-0.8        -0.7777778 ]
 [-0.8        -0.5555556 ]
 [-0.8        -0.33333334]
 [-0.8        -0.11111111]
 [-0.8         0.11111111]
 [-0.8         0.33333334]
 [-0.8         0.5555556 ]
 [-0.8         0.7777778 ]
 [-0.8         1.        ]
 [-0.6        -1.        ]
 [-0.6        -0.7777778 ]
 [-0.6        -0.5555556 ]
 [-0.6        -0.33333334]
 [-0.6        -0.11111111]
 [-0.6         0.11111111]
 [-0.6         0.33333334]
 [-0.6         0.5555556 ]
 [-0.6         0.7777778 ]
 [-0.6         1.        ]
 [-0.4        -1.        ]
 [-0.4        -0.7777778 ]
 [-0.4        -0.5555556 ]
 [-0.4        -0.33333334]
 [-0.4        -0.11111111]
 [-0.4         0.11111111]
 [-0.4         0.33333334]
 

In [13]:
test.x_unmeasured

array([[   0,  100],
       [   0,  200],
       [   0,  300],
       [   0,  400],
       [   0,  500],
       [   0,  600],
       [   0,  700],
       [   0,  800],
       [   0,  900],
       [   0, 1000],
       [  10,  100],
       [  10,  200],
       [  10,  300],
       [  10,  400],
       [  10,  500],
       [  10,  600],
       [  10,  700],
       [  10,  800],
       [  10,  900],
       [  10, 1000],
       [  20,  100],
       [  20,  200],
       [  20,  300],
       [  20,  400],
       [  20,  500],
       [  20,  600],
       [  20,  700],
       [  20,  800],
       [  20,  900],
       [  20, 1000],
       [  30,  100],
       [  30,  200],
       [  30,  300],
       [  30,  400],
       [  30,  500],
       [  30,  600],
       [  30,  700],
       [  30,  800],
       [  30,  900],
       [  30, 1000],
       [  40,  100],
       [  40,  200],
       [  40,  300],
       [  40,  400],
       [  40,  500],
       [  40,  600],
       [  40,  700],
       [  40,

In [ ]:
test._extract_spread_points(test.total_parameter_space)

(array([[   9,  225],
        [ 100, 2000],
        [   0, 1115]]),
 [np.int64(16234), np.int64(181900), np.int64(915)])